### ISSUE TITLE
add support for bundle --standalone

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm#1001]
for `cat .bundle/config`:

``` yaml

---
BUNDLE_PATH: bundle
BUNDLE_DISABLE_SHARED_GEMS: '1'
```

config looks like:

``` bash
GEM_HOME=$PWD/bundle/ruby/1.9.1/
GEM_PATH=$PWD/bundle/ruby/1.9.1/
PATH=$GEM_HOME/bin:$PATH
```

the path probably is build using `RbConfig::CONFIG['ruby_version']`
