### ISSUE TITLE
Segmentation fault: 11 

### ISSUE THREAD

**Issue by rich242** [rvm/rvm#1569]
I am trying to upgrade rvm but receive the following error every time.

``` bash
$ curl -L https://get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11517  100 11517    0     0    905      0  0:00:12  0:00:12 --:--:--  1457
Downloading RVM from wayneeseguin branch stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1488k  100 1488k    0     0  51633      0  0:00:29  0:00:29 --:--:-- 39131
bash: line 155: 12654 Segmentation fault: 11  $rvm_tar_command xzf ${rvm_archives_path}/${_file} ${rvm_tar_options:-} --strip-components 1
Could not extract RVM sources.
```

Does anyone have any information on how to resolve this?  I am running on a Mac OSX 10.7.5.

Additional information that may help:

Thanks

``` yaml
ruby-1.9.2-p180:

  system:
    uname:       "Darwin Rich-Harris 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.48(1)-release (x86_64-apple-darwin11)"
    zsh:         "/bin/zsh => zsh 4.3.11 (i386-apple-darwin11.0)"

  rvm:
    version:      "rvm 1.6.2 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p180"
    date:         "2011-02-18"
    platform:     "x86_64-darwin10.7.0"
    patchlevel:   "2011-02-18 revision 30909"
    full_version: "ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]"

  homes:
    gem:          "/Users/rharris/.rvm/gems/ruby-1.9.2-p180"
    ruby:         "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180"

  binaries:
    ruby:         "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180/bin/ruby"
    irb:          "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180/bin/irb"
    gem:          "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180/bin/gem"
    rake:         "/Users/rharris/.rvm/gems/ruby-1.9.2-p180/bin/rake"

  environment:
    PATH:         "/Users/rharris/.rvm/gems/ruby-1.9.2-p180/bin:/Users/rharris/.rvm/gems/ruby-1.9.2-p180@global/bin:/Users/rharris/.rvm/rubies/ruby-1.9.2-p180/bin:/Users/rharris/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/MacGPG2/bin"
    GEM_HOME:     "/Users/rharris/.rvm/gems/ruby-1.9.2-p180"
    GEM_PATH:     "/Users/rharris/.rvm/gems/ruby-1.9.2-p180:/Users/rharris/.rvm/gems/ruby-1.9.2-p180@global"
    MY_RUBY_HOME: "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180"
    IRBRC:        "/Users/rharris/.rvm/rubies/ruby-1.9.2-p180/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```
