### ISSUE TITLE
Requirements installation failed with Status 2 on Mac OS Sierra 10.12.5

### ISSUE THREAD

**Issue by KaraWalsh** [rvm/rvm#4116]
## Description

Trying to set up Ruby environment for first time, following directions from a Codecademy course. Typed `sudo rvm install 2.1.1` on command line, entered password, installation started but stopped with message `Requirements installation failed with Status 2`.

Here are the details:
```bash
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.12/x86_64/ruby-2.2.1.tar.bz2
Checking requirements for osx.
About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)
: 
-e:5: unknown regexp options - lcal
-e:6: unknown regexp options - lcal
-e:8: unknown regexp options - Cach
-e:9: syntax error, unexpected tLABEL
BREW_REPO = https://github.com/Homebrew/brew.freeze
                  ^
-e:9: unknown regexp options - gthb
-e:10: syntax error, unexpected tLABEL
CORE_TAP_REPO = https://github.com/Homebrew/homebrew-core.freeze
                      ^
-e:10: unknown regexp options - gthb
-e:32: syntax error, unexpected end-of-input, expecting keyword_end
-bash: line 32: end: command not found
-bash: line 34: def: command not found
-bash: line 35: escape: command not found
-bash: line 36: end: command not found
-bash: -c: line 38: syntax error near unexpected token `('
-bash: -c: line 38: `  def escape(n)'
Requirements installation failed with status: 2.
```

## Environment info

```yaml
system:

  system:
    uname:        "Darwin MacBook-Air-2.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "13 hours 23 minutes 42 seconds ago"
    path:         "/Users/karawalsh/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/karawalsh/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```
