### ISSUE TITLE
reporting autolibs status is broken

### ISSUE THREAD

**Issue by x-yuri** [rvm/rvm#4123]
So is `show` and `reset`, supposedly. I can reproduce it after `rvm get master`. 

## Steps to reproduce

```sh
$ rvm autolibs status
```

## Expected behavior

```yaml
---                                            
value: enable                                  
number: 4                                      
runner: ubuntu                                 
description: Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X).
```

## Actual behavior

```yaml
---
value: status
number: 
runner: 
description: 
```

The following changes fix it for `status`:

```diff
diff --git a/scripts/autolibs b/scripts/autolibs
index 7c0bdc6f..65b9b8f9 100755
--- a/scripts/autolibs
+++ b/scripts/autolibs
@@ -24,16 +24,18 @@ description: ${rvm_autolibs_flag_description}
 
 __rvm_autolibs()
 {
-  rvm_autolibs_flag="$1"
+  if [ "$1" != status ]; then
+    rvm_autolibs_flag="$1"
+  fi
   
   if
     __rvm_autolibs_translate
   then
     __rvm_autolibs_set
   else
-    case "${rvm_autolibs_flag:-help}" in
+    case "$1" in
       (show|status|reset)
-        __rvm_autolibs_${rvm_autolibs_flag}
+        __rvm_autolibs_$1
         ;;
       (help)
         rvm_help autolibs "$@"
```
